# SPDX-FileCopyrightText: 2023
#
# SPDX-License-Identifier: MIT

---
name: Build and Test Coverage Plugin

on: pull_request

jobs:
  coverage-build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build --no-daemon
        working-directory: "coverage-reporter"

      - name: Run Tests
        run: ./gradlew test --no-daemon
        working-directory: "coverage-reporter"
